services:
  app:
    image: mjulestek/profile-app:1.1
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mjulestek
      POSTGRES_PASSWORD: password123

volumes:
  postgres-data: