name: Complete CI/CD Pipeline Deployment on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to my GitHub repository
        uses: actions/checkout@v4

      - name: Set up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install all dependencies
        working-directory: application
        run: npm install

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/profile-app:1.1 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/profile-app:1.1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/profile-app:1.1
            docker stop profile-app || true
            docker rm profile-app || true
            docker run -d \
              --name profile-app \
              -p 80:3000 \
              ${{ secrets.DOCKER_USERNAME }}/profile-app:1.1